### ISSUE TITLE
I have a question about engine.py

### ISSUE THREAD

**Issue by Nastu-Ho** [xulianuwa/MCTformer#20]
line 177 and 178
Why do some cls_attentions maps need to flip and some don't?

**Comment by xulianuwa** [comment]
> line 177 and 178 Why do some cls_attentions maps need to flip and some don't?

https://github.com/xulianuwa/MCTformer/blob/12c6fdb30b5fa1a60cf7736e10069ff6ef843b49/datasets.py#L155-L156

It is because, as shown in the above lines, for each input, the original image and its flipped version are both used to generate cls_attention maps. Only the cls_attention map of the flipped image needs to be flipped back and then combined with the cls_attention map of the original image, to generate the final cls_attention map.
